name: Publish package

on:
  release:
    types: [published]

jobs:
  publish-npm:
    name: Publish to npm registry
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        # Since version 7.35.0 the `eslint-plugin-react` package contains a cyclic structure of the plugin object.
        # The `eslint-plugin-react@~7.34.0` package specifies the required `eslint` version up to 9, but not including it.
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build:swc && npm run build:tsc

      - name: Publish
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
